name: dart_stork_client
description: Dart package to access apps open APIs
version: 0.0.2
homepage: https://github.com/stork-delivery/dart_stork_client

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.1.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
